routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('users', 'UserController');

Route::resource('messages', 'MessageController');

app/Message.php
<?php

namespace App;

use Eloquent as Model;

/**
 * Class Book
 * @package App\Models
 * @version September 17, 2018, 1:00 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection GameNumber
 * @property \Illuminate\Database\Eloquent\Collection Inventory
 * @property \Illuminate\Database\Eloquent\Collection roleHasPermissions
 * @property \Illuminate\Database\Eloquent\Collection storeUsers
 * @property \Illuminate\Database\Eloquent\Collection userShifts
 * @property string game
 * @property float book_price
 * @property integer ticket_qty
 * @property float ticket_price
 * @property string image
 */
class Message extends Model
{

    public $table = 'messages';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    public $fillable = [
        'sender_user_id',
        'receiver_user_id',
        'message'
    ];

    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    
    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Validator;

class MessageController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $validator = Validator::make($request->all(), [
                    'sender_user_id' => 'required',
                    'receiver_user_id' => 'required',
                    'message' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect('/users')->with('Error', 'Message Not Delivered');
        } else {
            $epoch = strtotime(Carbon::now());
            $data = array(
                'sender_user_id' => $request->sender_user_id,
                'receiver_user_id' => $request->receiver_user_id,
                'message' => $request->message,
                'epoch' => $epoch
            );
            DB::table('messages')->insert($data);
            return redirect('/users')->with('success', 'Message Delivered successfully');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $users = DB::table('messages')
                ->join('users', 'messages.sender_user_id', '=', 'users.id')
                ->whereIn('sender_user_id', array(1, $id))
                ->whereIn('receiver_user_id', array(1, $id))
                ->orderBy('epoch', 'DESC')
                ->get(array(
                    'messages.id as message_id',
                    'first_name',
                    'sender_user_id',
                    'receiver_user_id',
                    'message',
                    'epoch'
                ));
                //print_r($users);
                //die();
        $receiverDetail = DB::table('users')
                ->where('id', $id)
                ->get();
        $senderDetail = DB::table('users')
                ->where('id', 1)
                ->get();
        return view('message/index', compact('users', 'receiverDetail', 'senderDetail'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $user = User::findOrFail($id);
        return view('message/create', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/message/create.blade.php
@extends('master/layout')

@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="card uper">
    <div class="card-header">
        Start Chatting
    </div>
    <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif
        <h4>Chat To: {{$user->first_name}} </h4>
        <form method="post" action="{{ route('messages.store') }}">
            <div class="form-group">
                @csrf
                <label for="name">Write Message:</label>
                <input type="text" class="form-control" name="message"/>
                <input type="hidden" name="receiver_user_id" value="{{$user->id}}"/>
                <input type="hidden" name="sender_user_id" value="1"/>
            </div>
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>
    </div>
</div>
@endsection

resources/views/message/index.blade.php
@extends('master/layout')

@section('content')
<style>
    .uper {
        margin-top: 40px;
    }
</style>
<div class="uper">
    @foreach($senderDetail as $senderDetails)
    <h3>Chatting History between <b>{{$senderDetails->first_name}}</b> &
    @endforeach
    
    @foreach($receiverDetail as $receiverDetails)
    <b>{{$receiverDetails->first_name}}</b></h3>
    @endforeach
    
    @if(session()->get('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}  
    </div><br />
    @endif
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Sender</td>
                <td>Message</td>
                <td colspan="2">Timestamp</td>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{$user->first_name}}</td>
                <td>{{$user->message}}</td>
                <td>{{$user->epoch}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div>
        @endsection